In [1]:
import numpy as np
    

In [6]:
y = np.linspace(start=0,stop=20,num=10,retstep=True)

In [7]:
y

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

In [12]:
z = np.arange(start=0, stop=20)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Reshaping

In [19]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
z = x.reshape((2,5))
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

** random no generation

In [21]:
np.random.rand(5)

array([0.72322658, 0.63064791, 0.49753073, 0.18252126, 0.56185847])

In [22]:
np.random.rand(5, 2)

array([[0.4675136 , 0.86133411],
       [0.34108373, 0.5893876 ],
       [0.24519639, 0.18911913],
       [0.73737831, 0.08056621],
       [0.27848989, 0.99652947]])

In [24]:
np.random.randn(5, 2)

array([[ 0.42442947,  0.29924397],
       [ 0.16535356, -1.15813518],
       [-0.62829167, -1.54638251],
       [ 0.07749302,  0.43553211],
       [-1.01139769,  0.29511243]])

In [27]:
np.random.randint(low=0, high=100, size=5)

array([ 8, 23, 39, 95, 75])

Seed 